### ISSUE TITLE
Converter will not convert

### ISSUE THREAD

**Issue by jayfallon** [vagnervjs/frame-player#5]
For the life of me I cannot convert any images to json using:

node app.js frameStart frameEnd img/ video04.json

When I open the video04.json file it show only:

{"frames":[]}

Installed mime via NPM, aside from that nothing else works. Thanks!

**Comment by oryan** [comment]
@vagnervjs is there an example of what this is supposed to look like?

I am using:
`$ node app.js 00 23 imgs/ json/video.json`
And just getting:
`Error: ENOENT, no such file or directory 'imgs/00'`

And there are most certainly images there.

If I use:
`$ node app.js 00.jpg 23.jpg imgs/ json/video.json`
I get:
`Converting file: 00.jpg
{ [Error: ENOENT, open 'json/video.json'] errno: -2, code: 'ENOENT', path: 'json/video.json' }`

If I use:
`$ node app.js 00.jpg 23.jpg imgs/ video.json`
I says it only converted one jpg and gives me an empty json.
`{"frames":[]}`

Any ideas?

![image](https://cloud.githubusercontent.com/assets/3709153/16399649/3fd22232-3c89-11e6-81c5-1423e60983c1.png)

**Comment by DanielRuf** [comment]
@oryan better open a new issue for this

**Comment by DanielRuf** [comment]
@oryan did you carefully read the instructions?

```
The parameters frameStart and frameEnd needs to be an integer number, that represents the numer of frame to start and to finish.

Example: node app.js 1 500 img/ video04.json
```

**Comment by oryan** [comment]
@DanielRuf yeah, I did. In my first example I was using integers. 

I figured it out. The problem is that the script is expecting non-padded numbers and no folder preceding the target json file.

I didn't use the video conversion method described in the instructions because I was creating my video in after effects so I simply exported an image sequence. This also allowed me to define all the compression settings a little more finely. After Effects pads the numbers so they stay in order and import correctly into other applications. 

The script expects a pretty specific naming convention. I wasn't aware of this until digging through it.

**Comment by DanielRuf** [comment]
@oryan At least I see no directory `json` and 00.jpg is not an integer but 0, 1 and so on are integer values.

**Comment by oryan** [comment]
@DanielRuf like I said in my post: `In my first example I was using integers.`
`$ node app.js 00 23 imgs/ json/video.json`

00 is an integer.

After that I tried a bunch of other things, with unexpected results.

Either way, I rewrote portions of that script and got it to function how I needed.
